services:
    mongo-db:
        image: "mongo:${MONGO_DB_TAG}"
        hostname: "mongo-db"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "root"
        restart: "always"
        volumes:
            - "./mongo-db:/data/db"

    mysql:
        image: "mysql:${MYSQL_TAG}"
        hostname: "mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        restart: "always"
        volumes:
            - "./mysql:/var/lib/mysql"

    orion-ld:
        image: "fiware/orion-ld:${ORION_LD_TAG}"
        hostname: "orion-ld"
        environment:
            ORIONLD_EXPERIMENTAL: "TRUE"
            ORIONLD_MONGO_HOST: "mongo-db"
            ORIONLD_MONGO_USER: "root"
            ORIONLD_MONGO_PASSWORD: "root"
        restart: "always"
        depends_on:
            - "mongo-db"

    keyrock:
        image: "fiware/idm:${KEYROCK_TAG}"
        hostname: "keyrock"
        environment:
            IDM_DB_HOST: "mysql"
            IDM_DB_USER: "root"
            IDM_DB_PASS: "root"
            IDM_ADMIN_EMAIL: "${KEYROCK_ADMIN_EMAIL}"
            IDM_ADMIN_PASS: "${KEYROCK_ADMIN_PASSWORD}"
            IDM_CORS_ENABLED: true
            IDM_CORS_ORIGIN: "*"
            IDM_CORS_METHODS: "GET"
        restart: "always"
        depends_on:
            - "mysql"

    nginx:
        image: "nginx:${NGINX_TAG}"
        hostname: "nginx"
        ports:
            - "443:443"
        restart: "always"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "/etc/letsencrypt:/etc/letsencrypt"
        depends_on:
            - "keyrock"

    ouranos-ws-api:
        image: "ouranos-ws-api"
        hostname: "ouranos-ws-api"
        restart: "always"
        volumes:
            - "./config/ouranos-ws-api/.env:/var/www/api/.env"
            - "./ouranos-ws-data-model:/var/www/data-models/ouranos-ws/1"
            - "./ouranos-ws-api-i4trust-module/I4Trust:/var/www/api/API/Modules/I4Trust"
            - "./service-account.json:/var/www/service-account.json"
        depends_on:
            - "keyrock"
            - "orion-ld"

    ouranos-ws-app:
        image: "ouranos-ws-app"
        hostname: "ouranos-ws-app"
        restart: "always"
        volumes:
            - "./config/ouranos-ws-app/config.js:/var/www/html/config.js"
        depends_on:
            - "keyrock"
            - "ouranos-ws-api"
